// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package models

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetAccountBalance(ctx context.Context, id uuid.UUID) (GetAccountBalanceRow, error)
	GetAccountByID(ctx context.Context, id uuid.UUID) (GetAccountByIDRow, error)
	GetAccountStatusHistory(ctx context.Context, affectedAccountID uuid.NullUUID) ([]GetAccountStatusHistoryRow, error)
	GetAllActiveAccounts(ctx context.Context) ([]GetAllActiveAccountsRow, error)
	GetInterestRates(ctx context.Context) ([]InterestRate, error)
	GetProfileByUserID(ctx context.Context, id uuid.UUID) (GetProfileByUserIDRow, error)
	GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error)
	GetTransactionsByAccountID(ctx context.Context, fromAccountID uuid.UUID) ([]GetTransactionsByAccountIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	SaveAccount(ctx context.Context, arg SaveAccountParams) (Account, error)
	SaveAuditLog(ctx context.Context, arg SaveAuditLogParams) error
	SaveInterestRate(ctx context.Context, arg SaveInterestRateParams) (InterestRate, error)
	SaveTransaction(ctx context.Context, arg SaveTransactionParams) (Transaction, error)
	SaveUser(ctx context.Context, arg SaveUserParams) (SaveUserRow, error)
	UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) error
	UpdateCalculationFrequency(ctx context.Context, arg UpdateCalculationFrequencyParams) error
	UpdateRate(ctx context.Context, arg UpdateRateParams) error
}

var _ Querier = (*Queries)(nil)
